name: Say hello to Miguel

on:
  push:
    branches:
      - main

jobs:
  hello-world-miguel:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to Miguel
        run: echo "Hello, Miguel Angel!"
      - name: Say hello to Miguel in Spanish
        run: |
          echo Hola Miguel Angel!
      - name: Display current date
        run: date