name: Say hello to Miguel

on:
  push:
    branches:
      - main

jobs:
  hello-world-miguel:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to Miguel
        run: echo "Hello, Miguel!"